#theme: jekyll-theme-minimal
remote_theme: pmarsceill/just-the-docs
title: DIGITAL DICTATORSHIP
description: Course site for GOVT 403

header_pages:
  - about.md
  - syllabus.md
  - lectures.md
  - Processing Raw Text.ipynb
  - resources.md

