#theme: jekyll-theme-minimal
remote_theme: pmarsceill/just-the-docs
title: DIGITAL DICTATORSHIP
description: Course site for GOVT 403
copyright: "2021"

header_pages:
  - about.md
  - syllabus.md
  - lectures.md
  - intro_to_text_as_data.md
  - Geometry_of_texts.md
  - intro_to_topic_modeling.md
  - resources.md

baseurl: /digital_dictatorship


# Information about where the book exists on the web
repository:
  url: https://fionashenbayh.github.io # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
