#theme: jekyll-theme-minimal
remote_theme: pmarsceill/just-the-docs
title: DIGITAL DICTATORSHIP
description: Course site for GOVT 403

header_pages:
  - about.md
  - syllabus.md
  - lectures.md
  - Processing_Raw_Text.ipynb
  - resources.md

# Information about where the book exists on the web
repository:
  url: https://fionashenbayh/GOVT-403 # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)

